version: '2'
services:
  network:
    build: network/
    image: ollebo/yun-network
    network_mode: host
    privileged: true
    environment:
      - WIFI_NAME=CGO3P_ROCK4B
      - WIFI_PASSWORD=0123456789
      - WIFI_DEVICE=wlan0
      - IPADDR=192.168.42.1/24        
  dhcpd:
    build: network
    privileged: true
    command:
     - dnsmasq
     - -d  
     - --dhcp-range=192.168.42.10,192.168.42.100
     - --dhcp-option=option:router,192.168.42.1
     - --dhcp-option=6,192.168.42.1,1.1.1.1
     - --log-queries 
     - --log-dhcp
    network_mode: host 
  api:
    build: .
    image: ollebo/yun-api
    volumes:
      - ./:/code
      - ./images:/images
    #command: tail -f /etc/fstab
    network_mode: host
    ports:
      - 8080:8080
    environment:
      - RTSP_STREAM=['rtsp://localhost:554/live']
    depends_on: 
      - ffmpeg
  rtsp:
    build: rtsp/
    image: ollebo/yun-rtsp
    environment:
      - RTSP_API=yes
      - RTSP_APIADDRESS=0.0.0.0:9997
      - RTSP_LOGLEVEL=info
    network_mode: host
  ffmpeg:
    build: ffmpeg/
    image: ollebo/ffmpeg
    network_mode: host
    privileged: true
    command: tail -f /etc/fstab
    volumes:
      - /dev:/dev
    #command: ffmpeg  -f v4l2 -input_format mjpeg  -video_size 1920x1080 -i /dev/video5 -vcodec libx264 -tune zerolatency   -f rtsp  rtsp://localhost:554/live
    depends_on:
      - rtsp
