version: '2'
services:
  network:
    build: network/
    image: ollebo/yun-network
    network_mode: host
    privileged: true
    environment:
      - WIFI_NAME=CGO3P_23145E
      - WIFI_PASSWORD=12345678
      - WIFI_DEVICE=wlan0
      - IPADDR=192.168.42.1/24        
  api:
    build: .
    image: ollebo/yun-api
    volumes:
      - ./:/code
      - ./images:/images
    #command: tail -f /etc/fstab
    network_mode: host
    ports:
      - 8080:8080
    environment:
      - RTSP_STREAM=['rtsp://localhost:554/live']
    depends_on: 
      - ffmpeg
  rtsp:
    build: rtsp/
    image: ollebo/yun-rtsp
    environment:
      - RTSP_API=yes
      - RTSP_APIADDRESS=0.0.0.0:9997
      - RTSP_LOGLEVEL=debug
    network_mode: host
  ffmpeg:
    build: ffmpeg/
    image: ollebo/ffmpeg
    network_mode: host
    privileged: true
    volumes:
      - /dev:/dev
    #command: ffmpeg -f v4l2 -i /dev/video3 -pix_fmt yuv420p -preset ultrafast -b:v 600k -f rtsp rtsp://localhost:554/live
    depends_on:
      - rtsp
